# Generated by Django 6.0.5 on 2026-05-23 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('team_a_count', models.IntegerField(default=0)),
                ('team_b_count', models.IntegerField(default=0)),
                ('winner_team', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_players', models.IntegerField(default=6)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_created_by', to=settings.AUTH_USER_MODEL)),
                ('team_a', models.ManyToManyField(related_name='games_team_a', to=settings.AUTH_USER_MODEL)),
                ('team_b', models.ManyToManyField(related_name='games_team_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
