# Generated by Django 6.0.5 on 2026-05-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_queue_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.queue'),
        ),
    ]
