# Generated by Django 6.0.3 on 2026-04-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loses',
            new_name='losses',
        ),
    ]
