# Generated by Django 6.0.4 on 2026-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_loses_user_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('avatar1', 'test'), ('avatar2', 'test2')], default='avatar1', max_length=69),
        ),
    ]
