# Generated by Django 6.0.4 on 2026-04-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatars/_.webp', upload_to='avatars/'),
        ),
    ]
