# Generated by Django 6.0.4 on 2026-04-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/speed.gif', upload_to='avatars/'),
        ),
    ]
